//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devart.AI.McpServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devart.AI.McpServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a new row into the specified table in {0} and returns the number of rows affected..
        /// </summary>
        public static string AddRowTool_Description {
            get {
                return ResourceManager.GetString("AddRowTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row added successfully. Rows affected: {0}..
        /// </summary>
        public static string AddRowTool_SuccessMessage {
            get {
                return ResourceManager.GetString("AddRowTool_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string ColumnsTool_ColumnNameHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_ColumnNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string ColumnsTool_DataTypeHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_DataTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string ColumnsTool_DefaultValueHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_DefaultValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of columns for the specified table in {0} as Markdown..
        /// </summary>
        public static string ColumnsTool_Description {
            get {
                return ResourceManager.GetString("ColumnsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ColumnsTool_DescriptionHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable.
        /// </summary>
        public static string ColumnsTool_NullableHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_NullableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Columns of the {0} table.
        /// </summary>
        public static string ColumnsTool_OutputHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ColumnsTool_SizeHeader {
            get {
                return ResourceManager.GetString("ColumnsTool_SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the configuration window for the MCP Server.
        /// </summary>
        public static string CommandLine_CommandConfigMcp {
            get {
                return ResourceManager.GetString("CommandLine_CommandConfigMcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run MCP Server.
        /// </summary>
        public static string CommandLine_CommandRunMcp {
            get {
                return ResourceManager.GetString("CommandLine_CommandRunMcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found: {0}..
        /// </summary>
        public static string CommandLine_ConfigFileNotFound {
            get {
                return ResourceManager.GetString("CommandLine_ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: {0}.
        /// </summary>
        public static string CommandLine_LogConfigurationError {
            get {
                return ResourceManager.GetString("CommandLine_LogConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server shutdown requested.
        /// </summary>
        public static string CommandLine_LogShutdown {
            get {
                return ResourceManager.GetString("CommandLine_LogShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting MCP server with config: {0}.
        /// </summary>
        public static string CommandLine_LogStartWithConfig {
            get {
                return ResourceManager.GetString("CommandLine_LogStartWithConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP server stopped gracefully.
        /// </summary>
        public static string CommandLine_LogStopped {
            get {
                return ResourceManager.GetString("CommandLine_LogStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error during MCP server execution..
        /// </summary>
        public static string CommandLine_LogUnhandledError {
            get {
                return ResourceManager.GetString("CommandLine_LogUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the full path to the configuration file. If the option is omitted or the specified file does not exist, the configuration file is searched first in the server folder, then in the &lt;ProgramData&gt; folder..
        /// </summary>
        public static string CommandLine_OptionFile {
            get {
                return ResourceManager.GetString("CommandLine_OptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the configuration to be used when starting the MCP server..
        /// </summary>
        public static string CommandLine_ParamConfigName {
            get {
                return ResourceManager.GetString("CommandLine_ParamConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devart AI MCP Server (ODBC).
        /// </summary>
        public static string CommandLine_RootCommand {
            get {
                return ResourceManager.GetString("CommandLine_RootCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]..
        /// </summary>
        public static string CommandLine_VerbosityOption {
            get {
                return ResourceManager.GetString("CommandLine_VerbosityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;McpServer&apos; section in appsettings.json is required..
        /// </summary>
        public static string Common_AppSettingsMcpServerSectionRequired {
            get {
                return ResourceManager.GetString("Common_AppSettingsMcpServerSectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings file not found: {0}..
        /// </summary>
        public static string Common_AppSettingsNotFound {
            get {
                return ResourceManager.GetString("Common_AppSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;dsn&apos; in configuration file must be set to the existing ODBC Data Source Name..
        /// </summary>
        public static string Common_ConfigFileDnsRequired {
            get {
                return ResourceManager.GetString("Common_ConfigFileDnsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file..
        /// </summary>
        public static string Common_ConfigFileInvalid {
            get {
                return ResourceManager.GetString("Common_ConfigFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid protocol type specified in the configuration file..
        /// </summary>
        public static string Common_ConfigFileInvalidProtocolType {
            get {
                return ResourceManager.GetString("Common_ConfigFileInvalidProtocolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration: {0}.
        /// </summary>
        public static string Common_ConfigInvalid {
            get {
                return ResourceManager.GetString("Common_ConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSN must be provided as the first argument..
        /// </summary>
        public static string Common_DsnRequired {
            get {
                return ResourceManager.GetString("Common_DsnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        public static string Common_NoDataAvailable {
            get {
                return ResourceManager.GetString("Common_NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL statements provided..
        /// </summary>
        public static string Common_NoSqlStatementsProvided {
            get {
                return ResourceManager.GetString("Common_NoSqlStatementsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly must be provided as the second argument..
        /// </summary>
        public static string Common_ReadOnlyRequired {
            get {
                return ResourceManager.GetString("Common_ReadOnlyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the configuration window for {0}..
        /// </summary>
        public static string ConfigTool_Description {
            get {
                return ResourceManager.GetString("ConfigTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the row count for the specified table in {0}..
        /// </summary>
        public static string CountRowsTool_Description {
            get {
                return ResourceManager.GetString("CountRowsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Count.
        /// </summary>
        public static string CountRowsTool_RowsCount {
            get {
                return ResourceManager.GetString("CountRowsTool_RowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        public static string CountRowsTool_TableName {
            get {
                return ResourceManager.GetString("CountRowsTool_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes one or more SQL-92 statements in a single transaction against {0} and returns the number of rows affected. Supported operations: {1}..
        /// </summary>
        public static string ExecuteNonQueryTool_Description {
            get {
                return ResourceManager.GetString("ExecuteNonQueryTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0} in your query is of type {1}, but only {2} statements are allowed in this tool..
        /// </summary>
        public static string ExecuteNonQueryTool_InvalidStatementTypeError {
            get {
                return ResourceManager.GetString("ExecuteNonQueryTool_InvalidStatementTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executed successfully. Rows affected: {0}..
        /// </summary>
        public static string ExecuteNonQueryTool_SuccessMessage {
            get {
                return ResourceManager.GetString("ExecuteNonQueryTool_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query completed successfully..
        /// </summary>
        public static string ExecuteReaderTool_CompletedMessage {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to data source....
        /// </summary>
        public static string ExecuteReaderTool_ConnectingMessage {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes SQL-92 SELECT statements against {0} and returns the result set as Markdown..
        /// </summary>
        public static string ExecuteReaderTool_Description {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SELECT query....
        /// </summary>
        public static string ExecuteReaderTool_ExecutingMessage {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_ExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT query in progress... ({0} seconds elapsed).
        /// </summary>
        public static string ExecuteReaderTool_InProgressMessage {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_InProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0} in your query is of type {1}, but only SELECT statements are allowed in this tool..
        /// </summary>
        public static string ExecuteReaderTool_InvalidStatementTypeError {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_InvalidStatementTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Result Set {0}.
        /// </summary>
        public static string ExecuteReaderTool_ResultSetHeader {
            get {
                return ResourceManager.GetString("ExecuteReaderTool_ResultSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes a stored procedure or scalar function against {0}. Required value of &apos;routineType&apos; parameter: {1}..
        /// </summary>
        public static string ExecuteRoutineTool_Description {
            get {
                return ResourceManager.GetString("ExecuteRoutineTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function executed successfully. Return value: {0}..
        /// </summary>
        public static string ExecuteRoutineTool_FunctionSuccessMessage {
            get {
                return ResourceManager.GetString("ExecuteRoutineTool_FunctionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid value of &apos;routineType&apos; parameter. Required value: {1}..
        /// </summary>
        public static string ExecuteRoutineTool_InvalidRoutineTypeError {
            get {
                return ResourceManager.GetString("ExecuteRoutineTool_InvalidRoutineTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure executed successfully..
        /// </summary>
        public static string ExecuteRoutineTool_ProcedureSuccessMessage {
            get {
                return ResourceManager.GetString("ExecuteRoutineTool_ProcedureSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine type {0} is currently not supported..
        /// </summary>
        public static string ExecuteRoutineTool_RoutineTypeNotSupported {
            get {
                return ResourceManager.GetString("ExecuteRoutineTool_RoutineTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule.
        /// </summary>
        public static string ForeignKeysTool_DeleteRuleHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_DeleteRuleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of foreign keys for the specified table in {0} as Markdown..
        /// </summary>
        public static string ForeignKeysTool_Description {
            get {
                return ResourceManager.GetString("ForeignKeysTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key column.
        /// </summary>
        public static string ForeignKeysTool_FkColumnHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_FkColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key name.
        /// </summary>
        public static string ForeignKeysTool_FkNameHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_FkNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Foreign keys of the {0} table.
        /// </summary>
        public static string ForeignKeysTool_OutputHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced column.
        /// </summary>
        public static string ForeignKeysTool_PkColumnHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_PkColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced schema.
        /// </summary>
        public static string ForeignKeysTool_PkSchemaHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_PkSchemaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced table.
        /// </summary>
        public static string ForeignKeysTool_PkTableHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_PkTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update rule.
        /// </summary>
        public static string ForeignKeysTool_UpdateRuleHeader {
            get {
                return ResourceManager.GetString("ForeignKeysTool_UpdateRuleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string IndexesTool_ColumnName {
            get {
                return ResourceManager.GetString("IndexesTool_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string IndexesTool_Columns {
            get {
                return ResourceManager.GetString("IndexesTool_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of indexes for the specified table in {0} as Markdown..
        /// </summary>
        public static string IndexesTool_Description {
            get {
                return ResourceManager.GetString("IndexesTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IndexesTool_IndexName {
            get {
                return ResourceManager.GetString("IndexesTool_IndexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string IndexesTool_IndexType {
            get {
                return ResourceManager.GetString("IndexesTool_IndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string IndexesTool_OrdinalPosition {
            get {
                return ResourceManager.GetString("IndexesTool_OrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Indexes of the {0} table.
        /// </summary>
        public static string IndexesTool_OutputHeader {
            get {
                return ResourceManager.GetString("IndexesTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves usage instructions for {0}..
        /// </summary>
        public static string InstructionsTool_Description {
            get {
                return ResourceManager.GetString("InstructionsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions resource {0} not found..
        /// </summary>
        public static string InstructionsTool_ResourceNotFound {
            get {
                return ResourceManager.GetString("InstructionsTool_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In all generated SQL queries, use quotes to escape identifiers. For example:.
        /// </summary>
        public static string InstructionsTool_SqlEscapingInstructions {
            get {
                return ResourceManager.GetString("InstructionsTool_SqlEscapingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported JSON parameter value type {0}. Only primitive values are supported..
        /// </summary>
        public static string JsonElementExtensions_UnsupportedJsonTypeError {
            get {
                return ResourceManager.GetString("JsonElementExtensions_UnsupportedJsonTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of primary keys for the specified table in {0} as Markdown..
        /// </summary>
        public static string PrimaryKeysTool_Description {
            get {
                return ResourceManager.GetString("PrimaryKeysTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Primary keys of the {0} table.
        /// </summary>
        public static string PrimaryKeysTool_OutputHeader {
            get {
                return ResourceManager.GetString("PrimaryKeysTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key column.
        /// </summary>
        public static string PrimaryKeysTool_PkColumnHeader {
            get {
                return ResourceManager.GetString("PrimaryKeysTool_PkColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key name.
        /// </summary>
        public static string PrimaryKeysTool_PkNameHeader {
            get {
                return ResourceManager.GetString("PrimaryKeysTool_PkNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of stored procedures and functions with their parameters in {0} as Markdown..
        /// </summary>
        public static string RoutinesTool_Description {
            get {
                return ResourceManager.GetString("RoutinesTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Routines.
        /// </summary>
        public static string RoutinesTool_OutputHeader {
            get {
                return ResourceManager.GetString("RoutinesTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        public static string RoutinesTool_ProcedureName {
            get {
                return ResourceManager.GetString("RoutinesTool_ProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string RoutinesTool_ProcedureParameters {
            get {
                return ResourceManager.GetString("RoutinesTool_ProcedureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string RoutinesTool_ProcedureSchema {
            get {
                return ResourceManager.GetString("RoutinesTool_ProcedureSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RoutinesTool_ProcedureType {
            get {
                return ResourceManager.GetString("RoutinesTool_ProcedureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RoutinesTool_Remarks {
            get {
                return ResourceManager.GetString("RoutinesTool_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the {0} server version..
        /// </summary>
        public static string ServerVersionTool_Description {
            get {
                return ResourceManager.GetString("ServerVersionTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## {0} Version: {1}.
        /// </summary>
        public static string ServerVersionTool_OutputHeader {
            get {
                return ResourceManager.GetString("ServerVersionTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        public static string SqlFormatter_NameNullOrEmpty {
            get {
                return ResourceManager.GetString("SqlFormatter_NameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the list of tables in {0} as Markdown..
        /// </summary>
        public static string TablesTool_Description {
            get {
                return ResourceManager.GetString("TablesTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Tables.
        /// </summary>
        public static string TablesTool_OutputHeader {
            get {
                return ResourceManager.GetString("TablesTool_OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TablesTool_Remarks {
            get {
                return ResourceManager.GetString("TablesTool_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Name.
        /// </summary>
        public static string TablesTool_TableName {
            get {
                return ResourceManager.GetString("TablesTool_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string TablesTool_TableSchema {
            get {
                return ResourceManager.GetString("TablesTool_TableSchema", resourceCulture);
            }
        }
    }
}
